### PR TITLE
Revert "major: assets should not be parsed"

### LINKED ISSUE #307: Dependencies required through `module-alias` are treated as asset in 0.22.0
## What's wrong

In the recent release of `nft@0.22.0` and Vercel internal builder update(<24hrs), users who deployed [RSSHub](https://github.com/DIYgod/RSSHub) on Vercel no longer works.
The function logs show that

```bash
2022-08-29T20:12:19.574Z	undefined	ERROR	Cannot find module 'got'
Require stack:
- /var/task/lib/utils/got.js
- /var/task/lib/middleware/parameter.js
- /var/task/lib/app.js
- /var/task/api/vercel.js
2022-08-29T20:12:19.574Z	undefined	ERROR	Did you forget to add it to "dependencies" in `package.json`?
RequestId: aecf3542-8033-4686-b5e8-30cdec421dc9 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Upon inspections, it's found that `nft@0.22.0` will categorise modules that are required through [`module-alias`](https://www.npmjs.com/package/module-alias) as `asset` and will be dropped. In the above log, `got` is treated as `asset` and removed from `node_modules`.

## Steps reproduce

Repo link to reproduce this issue [TonyRL/RSSHub-nft-repro](https://github.com/TonyRL/RSSHub-nft-repro)

1. Deploy it using <https://vercel.com/import/project?template=https://github.com/TonyRL/RSSHub-nft-repro>
2. Visit \<deployed domain\>/github/comments/vercel/nft/304
3. Expect the above logs

## Somes Observations

Since we also use `nft` as a source to minify our docker image, with a slight modification to the script, here are the `reasons` from `nft@0.21.0` and `nft@0.22.0`.
[reasons-v0.21.log](https://github.com/vercel/nft/files/9447867/reasons-v21.log)
[reasons-v0.22.log](https://github.com/vercel/nft/files/9447869/reasons-v22.log)

### Steps to reproduce these logs

1. `yarn`
2. `node scripts/docker/minify-docker.js > reasons-v0.22.log`
3. roll back to `nft@0.21.0` using `yarn add -D nft@0.21.0`
4. `node scripts/docker/minify-docker.js > reasons-v0.21.log`

### observations(cont.)

For simplicities, you can focus on `lib/utils/got.js`(our wrapper of `got`) only. In `nft@0.21.0`, `lib/utils/got.js` is a dependency and `got` is `resolve`:

```js
  'lib/utils/got.js' => {
    type: [ 'dependency' ],
    ignored: false,
    parents: Set(5) {
      'api/vercel.js',
      'lib/routes/docschina/jsweekly.js',
      'lib/routes/jinritoutiao/keyword.js',
      'lib/routes/shanbay/checkin.js',
      'lib/routes/universities/hit/jwc.js'
    }
  },
  ...
  'node_modules/got/package.json' => {
    type: [ 'resolve' ],
    ignored: false,
    parents: Set(27) {
      'lib/utils/got.js',
      'lib/routes/vscode/marketplace.js',
      'lib/routes/feed-the-beast/modpack.js',
      'lib/routes/gvm/index.js',
      'node_modules/got/dist/source/index.js',
      ...
    }
  },
```

In `nft@0.22.0`, `lib/utils/got.js` becomes an asset and `got` no longer appears in the `reasons` list:

```js
  'lib/utils/got.js' => {
    type: [ 'asset' ],
    ignored: false,
    parents: Set(1) { 'api/vercel.js' }
  },
```

If we require got using relative path instead of going through `module-alias` in `lib/middleware/parameter.js`(from `const got = require('@/utils/got');` to `const got = require('../utils/got');`) then `lib/utils/got.js` becomes one of the dependencies:

```js
  'lib/utils/got.js' => {
    type: [ 'asset', 'dependency' ],
    ignored: false,
    parents: Set(2) { 'api/vercel.js', 'lib/middleware/parameter.js' }
  },
```

and its dependency `got` will also be included in the `reasons`:
[reasons-v0.22-parameter.log](https://github.com/vercel/nft/files/9448083/reasons-v22-parameter.log)

```js
  'node_modules/got/package.json' => {
    type: [ 'resolve' ],
    ignored: false,
    parents: Set(24) {
      'lib/utils/got.js',
      'node_modules/got/dist/source/index.js',
      'node_modules/got/dist/source/create.js',
      ...
    }
  },
```

## Additional info

- `module-alias` works in the application by defining the alias in `lib/app.js`

```js
const moduleAlias = require('module-alias');
moduleAlias.addAlias('@', () => __dirname);
```

- Promoting the working deployment to production will not work as I believe Vercel's internal builder starts using `nft@0.22.0` in roughly <24hrs ago.

### PR DESCRIPTION
**Pull request by styfle**
Reverts vercel/nft#304 (partially)

There are too many corner cases that rely on the old behavior such as #307 so unfortunately we have to revert.

- Fixes #307 
- Related to https://github.com/i18next/next-i18next/issues/1940 
- Related to https://stackoverflow.com/questions/73554073/bug-with-next-i18next-and-deployment-on-vercel-recently

### CODE REVIEW

**Review by ijjk — APPROVED** [review]

File: src/analyze.ts [hunk 1]
```diff
@@ -430,7 +430,7 @@ export default async function analyze(id: string, code: string, job: Job): Promi
         !excludeAssetFiles.has(path.basename(name)) &&
         !name.endsWith('/')
       )
-      .forEach(file => deps.add(file));
+      .forEach(file => assets.add(file));
```
Comment (styfle) [inline src/analyze.ts:433]: I wonder if we should keep this as `deps` since that seems like a bug 🤔

Comment (styfle) [reply src/analyze.ts]: Confirmed this still works so I'l keep it as `deps`
